import LocalizedStrings from 'react-native-localization';

let strings = new LocalizedStrings({
  en: {
    Login: 'Login',
    LoginNow: 'Login Now',
    Dashboard: 'Dashboard',
    BatchScan: 'Batch Scan',
    SingleScan: 'Single Scan',
    FinishBatch: 'Finish Batch',
    ReviewAndConfirm: 'Review and Confirm',
    History: 'History',
    Search: 'Search',
    ScanIOL: 'ScanIOL',
    Settings: 'Settings',
    Sound: 'Sound',
    FaceIDenabled: 'Face ID enabled',
    ConfirmScanManually: 'Confirm scan manually',
    UserCredential: 'User credential',
    ResendFunctionality: 'Resend functionality',
    Language: 'Language',
    EnterUserName: 'Enter UserName',
    EnterPassword: 'Enter Password',
  },
  fr: {
    Login: 'Connexion',
    LoginNow: 'Connectez-vous maintenant',
    Dashboard: 'Tableau de bord',
    BatchScan: 'Analyse par lots ',
    SingleScan: ' Scan unique ',
    FinishBatch: 'Terminer le lot',
    ReviewAndConfirm: 'Vérifier et confirmer',
    History: 'Histoire',
    Search: 'Chercher',
    ScanIOL: 'Scanner la LIO',
    Settings: 'Paramètres',
    Sound: 'Son',
    FaceIDenabled: 'Face ID activé',
    ConfirmScanManually: "Confirmer l'analyse manuellement",
    UserCredential: "Identifiant de l'utilisateur",
    ResendFunctionality: 'Fonctionnalité de renvoi',
    Language: 'Langue',
    EnterUserName: "Saisissez votre nom d'utilisateur",
    EnterPassword: 'Entrer le mot de passe',
  },
  gm: {
    Login: 'Anmeldung',
    LoginNow: 'Jetzt einloggen',
    Dashboard: 'Armaturenbrett',
    BatchScan: 'Stapelscan ',
    SingleScan: ' Einzelscan ',
    FinishBatch: 'Charge beenden',
    ReviewAndConfirm: 'Überprüfen und bestätigen',
    History: 'Geschichte',
    Search: 'Suchen',
    ScanIOL: 'IOL scannen',
    Settings: 'Einstellungen',
    Sound: 'Klang',
    FaceIDenabled: 'Face ID aktiviert',
    ConfirmScanManually: 'Bestätigen Sie den Scan manuell',
    UserCredential: 'Benutzeranmeldeinformationen',
    ResendFunctionality: 'Funktionalität erneut senden',
    Language: 'Sprache',
    EnterUserName: 'Geben Sie den Benutzernamen ein',
    EnterPassword: 'Passwort eingeben',
  },
});

export default strings;
